steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '-t'
      - 'gcr.io/$PROJECT_ID/neuro-san-studio-react-flow:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/neuro-san-studio-react-flow:latest'
images:
  - 'gcr.io/$PROJECT_ID/neuro-san-studio-react-flow:latest'
options:
  machineType: 'E2_HIGHCPU_8'
timeout: '1800s'
